# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: hc0d3r
email: your-email@domain.com
description: Just another useless web
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hc0d3r.github.io" # the base hostname & protocol for your site
gems: ['jekyll-gist']
twitter_username: hc0d3r
github_username:  hc0d3r

# Build settings
markdown: kramdown
